version: '2'
services:
  zookeeper:
    image: sumglobal/rpi-zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: sumglobal/rpi-kafka
    ports:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      HOSTNAME_COMMAND: "route -n | awk '/UG[ \t]/{print $$2}'"
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_HEAP_OPTS: "-Xmx200M -Xms28M"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
