version: '2'
services:
  zookeeper:
    image: sumglobal/rpi-zookeeper
    ports:
      - "2181:2181"
    networks:
      static-network:
        ipv4_address: 172.168.2.20

  kafka:
    image: sumglobal/rpi-kafka
    hostname: kafka
    ports:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka 
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_HEAP_OPTS: "-Xmx200M -Xms28M"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      static-network:
        ipv4_address: 172.168.2.21

  kafka1:
    image: sumglobal/rpi-kafka
    hostname: kafka1
    ports:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka1 
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_HEAP_OPTS: "-Xmx200M -Xms28M"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      static-network:
        ipv4_address: 172.168.2.22

  kafka2:
    image: sumglobal/rpi-kafka
    hostname: kafka2
    ports:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka2 
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_HEAP_OPTS: "-Xmx200M -Xms28M"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      static-network:
        ipv4_address: 172.168.2.23

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.168.2.0/16 
          #docker-compose v3+ do not use ip_range
          #ip_range: 172.28.5.0/24
